#!/bin/bash

TMP_DIR=$(mktemp -d)

# Reading old and new commit hashes
read OLD_REV NEW_REV REF_NAME

# Clone the contents of the new commit into a temporary directory
git --work-tree="$TMP_DIR" checkout "$NEW_REV" -- .

# List of required files
REQUIRED_FILES=(".env.template" "docker-compose.yml" "Dockerfile")

# Checking the presence of all files
for FILE in "${REQUIRED_FILES[@]}"; do
    if [ ! -f "$TMP_DIR/$FILE" ]; then
        echo "Error: Missing required file $FILE"
        exit 1
    fi
done

# Checking for variables in .env.template
REQUIRED_VARS=("REACT_APP_PORT" "SUBTITLES_FRONTEND_PORT" "SUBTITLES_FRONTEND_VERSION")
for VAR in "${REQUIRED_VARS[@]}"; do
    if ! grep -q "^$VAR=" "$TMP_DIR/.env.template"; then
        echo "Error: Missing environment variable $VAR in .env"
        exit 1
    fi
done

echo "Pre-receive hook passed successfully."
exit 0
