# Use an official Node.js runtime as the base image
FROM node:lts-alpine AS build

# Set the working directory
WORKDIR /usr/src/app

# Copy app dependencies
COPY package.json ./ 
COPY package-lock.json ./ 

# Install dependencies
RUN npm install

# Copy the app source code
COPY . .

# Build the React app
RUN npm run build

# Use an official Nginx image for serving the app
FROM nginx:alpine AS stage-1

# Copy the build artifacts to Nginx's HTML folder
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the port for the app
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]