services:
  react-app:
    container_name: subtitle-project
    image: bneibaruch/subtitles_frontend:${SUBTITLES_FRONTEND_VERSION}
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "${SUBTITLES_FRONTEND_PORT}:3000"
    volumes:
      - .:/app
    stdin_open: true
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
