version: '3.8'

services:
  bssvr:
    container_name: subtitles
    image: bneibaruch/subtitles_backend:${BSSVR_BACKEND_VERSION}
    environment:
      BSSVR_PROFILE: prod
      GIN_MODE: ${BSSVR_GIN_MODE}
    ports:
      - "${BSSVR_BACKEND_PORT}:8080"
    restart: always
    depends_on:
      subtitles_db:
        condition: service_healthy
    links:
        - subtitles_db
    networks:
      - mynetwork

  subtitles_db:
    container_name: subtitles_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${BSSVR_DB_USER}
      POSTGRES_PASSWORD: ${BSSVR_DB_PASSWORD}
      POSTGRES_DB: ${BSSVR_DB}
    volumes:
      - $HOME${BSSVR_POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data
    ports:
      - "5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynetwork

networks:
  mynetwork:
