# Use an official Node runtime as the base image
FROM node:alpine

# Set the working directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install

# Add app files
COPY . .

ARG REACT_API_URL
ENV REACT_API_URL $REACT_API_URL
ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL $REACT_APP_API_BASE_URL
ARG REACT_APP_KEYCLOAK_CLIENT_ID
ENV REACT_APP_KEYCLOAK_CLIENT_ID $REACT_APP_KEYCLOAK_CLIENT_ID
ARG REACT_APP_KEYCLOAK_REALM
ENV REACT_APP_KEYCLOAK_REALM $REACT_APP_KEYCLOAK_REALM
ARG REACT_APP_KEYCLOAK_URL
ENV REACT_APP_KEYCLOAK_URL $REACT_APP_KEYCLOAK_URL
ARG REACT_APP_MQTT_PATH
ENV REACT_APP_MQTT_PATH $REACT_APP_MQTT_PATH
ARG REACT_APP_MQTT_PORT
ENV REACT_APP_MQTT_PORT $REACT_APP_MQTT_PORT
ARG REACT_APP_MQTT_PROTOCOL
ENV REACT_APP_MQTT_PROTOCOL $REACT_APP_MQTT_PROTOCOL
ARG REACT_APP_MQTT_URL
ENV REACT_APP_MQTT_URL $REACT_APP_MQTT_URL

# Build the React app
RUN npm install -g serve
RUN npm run build -- prod

# Set the command to run the application
CMD ["serve", "-s", "build"]
