services:
  subtitles_frontend:
    container_name: subtitles_frontend
    image: bneibaruch/subtitles_frontend:${SUBTITLES_FRONTEND_VERSION}
    ports:
      - "${SUBTITLES_FRONTEND_PORT}:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "10m"
        max-file: "3"
    networks:
      - subtitles-network

networks:
  subtitles-network:
    name: subtitles-network
    driver: bridge
