openapi: 3.0.3
info:
  title: Broadcast Subtitles Server API
  description: |-
    This is a Subtitle Server API based on the OpenAPI 3.0 specification.  
  
  version: "0.1"
servers:
  - url: https://domain/api/v1
tags:
  - name: books
    description: Access and manage book content
  - name: bookmarks
    description: Access and manage bookmark
paths:
  /books:
    put:
      tags:
        - books
      summary: Update an book content by id
      description: Update an book content by id
      operationId: updateBook
      requestBody:
        required: true
        description: Update an book content by id
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookPutRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookResponse'
        '400':
          description: Invalid request value
        '404':
          description: Book not found
        '405':
          description: Validation http method
      security:
        - bearerAuth:
            - write:books
            - read:books
    post:
      tags:
        - books
      summary: Add an book content
      description: Add an book content
      operationId: addBook
      requestBody:
        required: true
        description: Add an book content
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasicBook'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookResponse'
        '400':
          description: Invalid request value
        '405':
          description: Invalid http method
      security:
        - bearerAuth:
            - write:books
            - read:books
    get:
      tags:
        - books
      summary: Finds book
      description: Finds book
      operationId: findBook
      parameters:
        - name: limit
          in: query
          description: page size for pagination
          required: false
          explode: true
          schema:
            type: string
        - name: start
          in: query
          description: start page
          required: false
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookResponse'
        '400':
          description: Invalid request query
        '404':
          description: Book not found
        '405':
          description: Invalid http method
      security:
        - bearerAuth:
            - read:books
  /bookmarks:
    put:
      tags:
        - bookmarks
      summary: Update an bookmark content by id
      description: Update an bookmark by id
      operationId: updateBookmark
      requestBody:
        required: true
        description: Update an bookmark by id
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookmarkPutRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookmarkResponse'
        '400':
          description: Invalid request value
        '404':
          description: Book not found
        '405':
          description: Validation http method
      security:
        - bearerAuth:
            - write:books
            - read:books
    post:
      tags:
        - bookmarks
      summary: Add an bookmark
      description: Add an bookmark
      operationId: addBookmark
      requestBody:
        required: true
        description: Add an bookmark
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasicBookmark'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookmarkResponse'
        '400':
          description: Invalid request value
        '405':
          description: Invalid http method
      security:
        - bearerAuth:
            - write:books
            - read:books
    get:
      tags:
        - bookmarks
      summary: Finds book in hebrew by id
      description: Finds book in hebrew by id
      operationId: findBookInHebrewById
      parameters:
        - name: limit
          in: query
          description: page size for pagination
          required: false
          explode: true
          schema:
            type: string
        - name: start
          in: query
          description: start page
          required: false
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookmarkResponse'
        '400':
          description: Invalid request query
        '404':
          description: Book not found
        '405':
          description: Invalid http method
      security:
        - bearerAuth:
            - read:books
  /archive:
    get:
      tags:
        - archive
      summary: Get archive information
      description: all archive information or some by filter
      operationId: findArchive
      parameters:
        - name: content
          in: query
          description: text to search for the filter
          required: false
          explode: true
          schema:
            type: string
        - name: author
          in: query
          description: author name to search for the filter
          required: false
          explode: true
          schema:
            type: string
        - name: type
          in: query
          description: type name to search for the filter
          required: false
          explode: true
          schema:
            type: string
        - name: book_title
          in: query
          description: book title to search for the filter
          required: false
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArchiveResponse'
        '400':
          description: Invalid request query
        '405':
          description: Invalid http method
      security:
        - bearerAuth:
            - read:books
components:
  schemas:
    BasicBook:
      type: object
      required:
        - author
        - title
        - content
        - slides
      properties:
        author:
          type: string
          description: book author
          example: "קלטות רבש"
        title:
          type: string
          description: book title
          example: "001_heb_o_rb_bs-tes-04_1"
        content:
          type: string
          description: book content
          example: "%author קלטות רבש %book 001_heb_o_rb_bs-tes-04_1"
        slides:
          type: string
          example: "[{page: 0
                    letter: 0
                    subletter: 1
                    revert: 1
                    content: <b>חלק רביעי ~
                    }]"
    BookPutRequest:
      allOf:     
        - $ref: '#/components/schemas/BasicBook'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
              example: 10
    BookResponse:
      allOf:     
        - $ref: '#/components/schemas/BookPutRequest'
        - type: object
          required:
            - created_at
            - updated_at
          properties:
            created_at:
              type: string
              format: date-time
              example: "2021-06-20T01:02:03+00:00"
            updated_at:
              type: string
              format: date-time
              example: "2021-06-20T01:02:03+00:00"
    BasicBookmark:
      type: object
      required:
        - author
        - book
        - book_name
        - page
        - letter
      properties:
        author:
          type: string
          description: book author
          example: "כתובות מייל"
        book:
          type: string
          description: book path
          example: "/books/1201"
        book_name:
          type: string
          description: book name
          example: "לכנסים רישום הנהלה והפצה"
        page:
          type: integer
          format: int64
          example: 232
        letter:
          type: string
          description: letter
          example: "0-38"
    BookmarkPutRequest:
      allOf:     
        - $ref: '#/components/schemas/BasicBookmark'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
              example: 10
    BookmarkResponse:
      allOf:    
        - $ref: '#/components/schemas/BookmarkPutRequest'
        - type: object
          required:
            - created_at
            - updated_at
          properties:
            created_at:
              type: string
              format: date-time
              example: "2021-06-20T01:02:03+00:00"
            updated_at:
              type: string
              format: date-time
              example: "2021-06-20T01:02:03+00:00"
    ArchiveResponse:
      allOf:
        - type: object
          required:
            - text
            - author
            - type
            - book_title
          properties:
            text:
              type: string
              description: book content
              example: ".1 והמשכילים יזהירו כזוהר הרקיע. המשכילים, הם המסתכלים בחכמה שהשיגו, כי חכמה מכונה אור העיניים, והשגתה מכונה הסתכלות. למה לא כתוב, יאירו? אלא, שמאירים ומתנוצצים בזיווה"
            author:
              type: string
              description: author name
              example: "זוהר לעם - כרכים א-ד"
            type:
              type: string
              description: content type
              example: "letter"
            book_title:
              type: string
              description: book title
              example: "כרך ד' - פרשת שמות"
  securitySchemes:
    bearerAuth:
      bearerFormat: auth-scheme
      description: 'Bearer HTTP authentication through keycloak. Allowed headers -- Authorization: Bearer <api_key>'
      scheme: bearer
      type: http
