version: '3.7'

services:
  subtitles_backend:
    restart: unless-stopped
    container_name: subtitles_backend
    image: bneibaruch/subtitles_backend:${SUBTITLES_BACKEND_VERSION}
    environment:
      GIN_MODE: release
      BSSVR_LOG_LEVEL: debug
      BSSVR_POSTGRES_URI: ${SUBTITLES_POSTGRES_URI}
      BSSVR_KEYCLOAK_URI: ${SUBTITLES_KEYCLOAK_URI}
      BSSVR_BACKEND_PORT: ${SUBTITLES_BACKEND_PORT}
    ports:
      - "${SUBTITLES_BACKEND_PORT}:${SUBTITLES_BACKEND_PORT}"
    #depends_on:
    #  subtitles_backend_db:
    #    condition: service_healthy
    networks:
      - subtitles-network
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

#  subtitles_backend_db:
#    restart: unless-stopped
#    container_name: subtitles_backend_db
#    image: postgres:16
#    shm_size: 1g
#    environment:
#      POSTGRES_USER: ${SUBTITLES_DB_USER}
#      POSTGRES_PASSWORD: ${SUBTITLES_DB_PASSWORD}
#      POSTGRES_DB: ${SUBTITLES_DB}
#    ports:
#      - "6363:5432"
#    volumes:
#      - /root/configs/subtitles_backend/data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD", "pg_isready", "-U", "postgres"]
#      interval: 10s
#      timeout: 10s
#      retries: 5
#    networks:
#      - subtitles-network

networks:
  subtitles-network:
    name: subtitles-network
    external: true
