name: Backend CI/CD
on:
  workflow_dispatch:
    # you can add push/pr triggers here
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run backend tests
        run: |
          cd backend
          go test ./...

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.BBDEPLOYMENT_DOCKERHUB_USERNAME }}
          password: ${{ secrets.BBDEPLOYMENT_DOCKERHUB_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: |
            bneibaruch/subtitles_backend:latest
            bneibaruch/subtitles_backend:gh_${{ github.run_number }}
          build-args: |
            build_number=gh_${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy backend over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.BBDEPLOYMENT_SSH_PRIVATE_KEY }}
          proxy_host: ${{ secrets.SSH_PROXY_HOST }}
          proxy_username: ${{ secrets.SSH_PROXY_USERNAME }}
          proxy_key: ${{ secrets.BBDEPLOYMENT_SSH_PRIVATE_KEY }}
          script: |
            cd /root/configs/subtitles_backend
            sed -i "s/SUBTITLES_VERSION.*/SUBTITLES_VERSION=gh_${{ github.run_number }}/g" .env
            docker compose pull subtitles_backend
            docker compose up -d subtitles_backend
