name: Frontend CI/CD
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install and test frontend
        run: |
          cd frontend
          npm ci
          npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.BBDEPLOYMENT_DOCKERHUB_USERNAME }}
          password: ${{ secrets.BBDEPLOYMENT_DOCKERHUB_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: true
          tags: |
            bneibaruch/subtitles_frontend:latest
            bneibaruch/subtitles_frontend:gh_${{ github.run_number }}
          build-args: |
            build_number=gh_${{ github.run_number }}
            REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy frontend over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.BBDEPLOYMENT_SSH_PRIVATE_KEY }}
          script: |
            cd /root/configs/subtitles_frontend
            sed -i "s/SUBTITLES_VERSION.*/SUBTITLES_VERSION=gh_${{ github.run_number }}/g" .env
            docker compose down subtitles_frontend || true
            docker compose pull subtitles_frontend
            docker compose up -d subtitles_frontend
